# Generated by Django 4.1 on 2022-08-11 03:09

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Developer",
            fields=[
                ("name", models.CharField(max_length=60)),
                (
                    "username",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("country", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Hackathon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("motto", models.TextField()),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("location", models.TextField()),
                ("website", models.URLField(blank=True)),
                ("logo", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "developer",
                    models.ForeignKey(
                        on_delete=models.SET(api.models.get_sentinel_dev),
                        to="api.developer",
                    ),
                ),
                (
                    "hackathon",
                    models.ForeignKey(
                        on_delete=models.SET(api.models.get_sentinel_hackathon),
                        to="api.hackathon",
                    ),
                ),
            ],
            options={
                "ordering": ["-score"],
            },
        ),
        migrations.AddField(
            model_name="hackathon",
            name="participants",
            field=models.ManyToManyField(through="api.Participant", to="api.developer"),
        ),
        migrations.AlterUniqueTogether(
            name="hackathon",
            unique_together={("name", "location")},
        ),
    ]
