# Generated by Django 4.1 on 2022-08-11 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hackathon",
            options={"ordering": ["-date_start", "-date_end"]},
        ),
    ]
