# Generated by Django 4.1 on 2022-08-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_hackathon_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="developer",
            name="picture",
            field=models.TextField(blank=True),
        ),
    ]
