# Generated by Django 4.1 on 2022-08-12 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_hackathon_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="score",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(1000)]
            ),
        ),
    ]
