# Generated by Django 4.1 on 2022-08-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_developer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="developer",
            name="country",
            field=models.TextField(blank=True, null=True),
        ),
    ]
