# Generated by Django 4.1 on 2022-08-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_developer_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="developer",
            name="country",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="developer",
            name="name",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="developer",
            name="picture",
            field=models.TextField(blank=True),
        ),
    ]
